spring.application.name=Module4
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aston_learn_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.mail.properties.mail.smtp.socketFactory.port=465
#Kafka
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.kafka.bootstrap-servers=localhost:9092