spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aston_learn_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# Настройка сервера
server:
  port: 8081
  servlet:
    context-path: /module4

# Настройка Kafka
kafka:
  bootstrap-servers: localhost:9092

# Настройка Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/