### Добавление нового пользователя
POST http://localhost:8080/module4/users
Content-Type: application/json

{
  "name": "Test",
  "email": "ega007.m@yandex.ru",
  "age": 29
}

### Получение списка всех пользователей
GET http://localhost:8080/module4/users

### Удаление пользователя
DELETE http://localhost:8080/module4/users/5

### Получение пользователя по ID
GET http://localhost:8080/module4/users/2

### Обновление пользователя
PUT http://localhost:8080/module4/users/2
Content-Type: application/json

{
  "name": "Test",
  "email": "ega007.m@yandex.ru",
  "age": 18
}

### Отправка произвольного текстового сообщения через тег MESSAGE
POST http://localhost:8080/module4/notifications/message
Content-Type: application/json

{
  "email": "ega007.m@yandex.ru",
  "operation": "MESSAGE:Привет! Это тестовое сообщение."
}